---
# Handlers for role: wazuh
# ==============================================================================

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart wazuh-indexer
  ansible.builtin.service:
    name: wazuh-indexer
    state: restarted

- name: Restart wazuh-manager
  ansible.builtin.service:
    name: wazuh-manager
    state: restarted

- name: Restart filebeat
  ansible.builtin.service:
    name: filebeat
    state: restarted

- name: Restart wazuh-dashboard
  ansible.builtin.service:
    name: wazuh-dashboard
    state: restarted
